package com.example.ido.view;

import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.example.ido.R;
import com.example.ido.R.id;
import com.example.ido.R.layout;
import com.example.ido.R.menu;
import com.example.ido.controller.ApplicationNavigationHandler;

import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Environment;
import android.os.Handler;
import android.app.ActionBar;
import android.app.Activity;
import android.content.Intent;
import android.database.Cursor;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.Adapter;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.ListView;
import android.widget.RadioButton;
import android.widget.RelativeLayout;
import android.widget.SimpleCursorAdapter;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.TextView;
import android.widget.Toast;

public class ViewAllGroupsActivity extends GeneralActivity {
	
	// VARIABLES DEFINED HERE
	int count = 0;
	// The cursor for query all groups from database
	private Cursor allGroupsCursor;
	
	// Adapter for All Groups List View
	private SimpleCursorAdapter allGroupsListViewAdapter;
	
	// All Groups List View
	private ListView allGroupsListView;
	
	

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_view_groups);
		//Function called to create set up a button
		setupMessageButton();

		};
		

		
		private void setupMessageButton(){
			//get ID of the button we're working with
			Button messageButton = (Button) findViewById(R.id.button1);
			
			//sets up an on click listener which will give the button attributes
			messageButton.setOnClickListener(new View.OnClickListener() {

				@Override
				public void onClick(View v) {
					//increase count
					count++;
					
					Handler handler = new Handler();
					
					//runnable set up to hold code which will fun after the handler
					Runnable r = new Runnable() {
						
						@Override
						public void run() {
							if (count == 1)
							{
								//Writes a one into the xml file
								xmlFormater(1);
								//toast to show confirmation of choice
								Toast.makeText(getApplicationContext(), "Yes", Toast.LENGTH_SHORT).show();
								//resets count
								count = 0;
							}
						}
					};
					//if user clicks once
					if(count == 1){
						//delay set up to check if user clicks twice within .25 seconds
						handler.postDelayed(r, 250);
						
						
					}
					//if user clicks twice
					else if (count == 2){
						//Writes a two into the xml file
						xmlFormater(2);
						//toast to show confirmation of choice
						Toast.makeText(getApplicationContext(), "No", Toast.LENGTH_SHORT).show();
						//resets count
						count = 0;
					}

				}	
			});
		}
		
		//Checks if external storage is available for read and write
		public boolean isExternalStorageWritable() {
		    String state = Environment.getExternalStorageState();
		    if (Environment.MEDIA_MOUNTED.equals(state)) {
		        return true;
		    }
		    return false;
		}
		
		void fileWriter(String instance){
		
				// Format of date
				SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyyy-mm-dd hh:mm:ss");
				
				// Create a new date object 
				Date date = new Date();
				
				// Get the daate and format it 
				String dateFormatted = DATE_FORMAT.format(date);
				
				// Get the path/directory of the external storage
				String root = Environment.getExternalStorageDirectory().toString();
				
				// Path/directory where we want to save the file
				File fileDir = new File(root + "/odk/instances");
				
				// Make the directory if it does not exist
				fileDir.mkdirs();
				
				// Name of the file with the date formated and the file extension
				String fileName = "form" + dateFormatted + ".xml";
				
				// Create a new File object with the directory specified in fileDir and the name in fileName
				File file = new File(fileDir,fileName);
				
				// Check to avoid duplicate files
				if(file.exists())
				{
				
					file.delete();
				}
				try
				{	
					// Write the file to the SD card on the phone
					FileOutputStream out = new FileOutputStream(file);
					out.write(instance.getBytes());
					out.close();
				}
				catch(Exception e)
				{
					e.printStackTrace();
				}

		}
		
		//this function takes input generated by the blue toothdevice and creates an instance of a form using xml format.
		public void xmlFormater(int input){
			

			//xml instance template;
			
			//Log.d("Elias",Environment.getExternalStorageDirectory().getAbsolutePath());//trouble shooting line.
			
			//xmlTest is an example of a form, here its hard coded. ideally this form would be imported from formhub with the fields 
			//pre-filled.
			String xmlTest="<?xml version='1.0' ?><testform1 id='testform1'><formhub><uuid>1d01462f8b4446caa6431cdcbd7849ba</uuid></formhub><correct_behavior>%s</correct_behavior><end>2014-03-15T10:00:14.671-07</end><meta><instanceID>uuid:02e0e664-5198-437e-a231-88fb300dc62a</instanceID></meta></testform1>";
			
			
			// variable formInstance holds the filled out form using the input from the bluetooth device. 
			String formInstance;
			
			//"if/else" - statement adds a 1 or a 2 to the xml instance
			if(input == 1){
				 formInstance = String.format(xmlTest, "1");
			}//end if
			else{
				//this is for a "no" response, will insert 2 in the form.
				 formInstance = String.format(xmlTest, "2");
			}//end else
			
			//formInstance is sent to fileWriter() function to write the file.
			fileWriter(formInstance);
			
		}//end xmlFormater()
		
}
